apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-volume-mysql
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/lv-mysql
  persistentVolumeReclaimPolicy: Recycle
