# ------------------------------------------------------------#
# Template Version
# ------------------------------------------------------------#
AWSTemplateFormatVersion: 2010-09-09
# ------------------------------------------------------------#
# Description Section
# ------------------------------------------------------------#
Description:
  EC2 Create
# ------------------------------------------------------------#
# Parameters Section
# ------------------------------------------------------------#
Parameters:
# ------------------------------------------------------------#
# Common Input Parameters
# ------------------------------------------------------------#
  SecurityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>
# ------------------------------------------------------------#
# Resources Section
# ------------------------------------------------------------#
Resources:
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: template
      LaunchTemplateData:
        BlockDeviceMappings:
          - DeviceName: /dev/sda1
            Ebs:
              VolumeSize: 8
              VolumeType: gp2
        DisableApiTermination: true
        IamInstanceProfile:
          Name: InstanceProfile
        ImageId: ami-045f38c93733dd48d
        InstanceType: t2.micro
        EbsOptimized: false
        InstanceInitiatedShutdownBehavior: stop
        KeyName: key
        Monitoring:
          Enabled: true
        CreditSpecification:
          CpuCredits: unlimited
        Placement:
          Tenancy: default
        SecurityGroupIds: !Ref SecurityGroupIds
        UserData: !Base64
          Fn::Sub: |
            #!/bin/bash -xe
            sudo yum update -y
            sudo yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
            sudo systemctl enable amazon-ssm-agent
            sudo systemctl start amazon-ssm-agent
            sudo systemctl status amazon-ssm-agent
            sudo yum install -y https://s3.amazonaws.com/amazoncloudwatch-agent/centos/amd64/latest/amazon-cloudwatch-agent.rpm