# ------------------------------------------------------------#
# Template Version
# ------------------------------------------------------------#
AWSTemplateFormatVersion: 2010-09-09
# ------------------------------------------------------------#
# Description Section
# ------------------------------------------------------------#
Description:
  SSM Parameter Create
# ------------------------------------------------------------#
# Input Parameters
# ------------------------------------------------------------# 
Parameters:
  MasterUserName:
    Type: String
    NoEcho: true
    MinLength: 1
    MaxLength: 16
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
# ------------------------------------------------------------#
#  SSM Parameter
#  Note: ssm secure string is not cfn support. 2019/12/15. To create a secure string, execute the following command.
#        aws ssm put-parameter --name MasterUserPassword --type SecureString --value "your pasword"
# ------------------------------------------------------------#
Resources:
  Parameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: MasterUsername
      Type: String
      Value: !Ref MasterUserName
      Description: MasterUsername for RDS