# ------------------------------------------------------------#
# Template Version
# ------------------------------------------------------------#
AWSTemplateFormatVersion: 2010-09-09
# ------------------------------------------------------------#
# Description Section
# ------------------------------------------------------------#
Description:
  NetworkAcl Create
# ------------------------------------------------------------#
# Metadata Section
# ------------------------------------------------------------#
Metadata:
# ------------------------------------------------------------#
# Interface
# ------------------------------------------------------------# 
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      - Label:
          default: NetworkACL Configuration
        Parameters:
          - VpcId
          - NetworkAclTag
      - Label:
          default: SubnetNetworkAclAssociation Configuration
        Parameters:
          - SubnetId
# ------------------------------------------------------------#
# Parameters Section
# ------------------------------------------------------------#
Parameters:
# ------------------------------------------------------------#
# VpcId Parameter
# ------------------------------------------------------------#
  VpcId:
    Type: AWS::EC2::VPC::Id
# ------------------------------------------------------------#
# NetworkAcl Input Parameters
# ------------------------------------------------------------#
  NetworkAclTag:
    Type: String
    Description: Rsource Name Tag
  SubnetId:
    Type: List<AWS::EC2::Subnet::Id>
# ------------------------------------------------------------#
# Resources Section
# ------------------------------------------------------------#
Resources:
# ------------------------------------------------------------#
# NetworkACL
# ------------------------------------------------------------#
  NetworkAcl:
    Type: AWS::EC2::NetworkAcl    
    DeletionPolicy: Delete
#    Condition: useNetworkAcl
    Properties: 
      VpcId: !Ref VpcId
      Tags: 
        - Key: Name
          Value: !Ref NetworkAclTag
# ------------------------------------------------------------#
  NetworkAclEntry01:
    Type: AWS::EC2::NetworkAclEntry
    DeletionPolicy: Delete
#    Condition: useNetworkAcl
    Properties: 
      CidrBlock: 0.0.0.0/0
      Egress: true
      NetworkAclId: !Ref NetworkAcl
      Protocol: -1
      RuleAction: allow
      RuleNumber: 100
# ------------------------------------------------------------#
  NetworkAclEntry02:
    Type: AWS::EC2::NetworkAclEntry
    DeletionPolicy: Delete
#    Condition: useNetworkAcl
    Properties: 
      CidrBlock: 0.0.0.0/0
      Egress: false
      NetworkAclId: !Ref NetworkAcl
      Protocol: -1
      RuleAction: allow
      RuleNumber: 100
# ------------------------------------------------------------#
  SubnetNetworkAclAssociation01:
    Type: AWS::EC2::SubnetNetworkAclAssociation
#    Condition: isSubnetId01
    Properties: 
      NetworkAclId: !Ref NetworkAcl
      SubnetId: !Ref SubnetId