# ------------------------------------------------------------#
# Template Version
# ------------------------------------------------------------#
AWSTemplateFormatVersion: 2010-09-09
# ------------------------------------------------------------#
# Description Section
# ------------------------------------------------------------#
Description: 
  Alarm Create
# ------------------------------------------------------------#
# Metadata Section
# ------------------------------------------------------------#
# ------------------------------------------------------------#
# Resources Section
# ------------------------------------------------------------#
Resources:
  Alarm:
    Type: AWS::CloudWatch::Alarm
    Properties: 
      ActionsEnabled: False
      AlarmActions: 
        - arn:aws:sns:ap-northeast-1:123456789012:test
      AlarmDescription: sample instance alarm 
      AlarmName: CPUUtilization-instance
      ComparisonOperator: GreaterThanThreshold
      DatapointsToAlarm: 1
      Dimensions: 
        - Name: InstanceId
          Value: i-00f6ebb246fa5dd62
#      EvaluateLowSampleCountPercentile: String
      EvaluationPeriods: 3
#      ExtendedStatistic: String
      InsufficientDataActions: 
        - arn:aws:sns:ap-northeast-1:123456789012:test
      MetricName: CPUUtilization
#      Metrics: 
#        - MetricDataQuery
      Namespace: AWS/EC2
      OKActions: 
        - arn:aws:sns:ap-northeast-1:123456789012:test
      Period: 60
      Statistic: Average
      Threshold: 80
#      ThresholdMetricId: String
      TreatMissingData: missing
#      Unit: String