AWSTemplateFormatVersion: "2010-09-09"
Description:
  SSM Parameter Create

# ------------------------------------------------------------#
# Input Parameters
# ------------------------------------------------------------# 
Parameters:
  Enviroment:
    Type: String
    NoEcho: No
    MinLength: 1
    MaxLength: 16
    Default: "enviroment"
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: "Enviroment name must begin with a letter and contain only alphanumeric characters."
# ------------------------------------------------------------#
#  SSM Parameter
# ------------------------------------------------------------#
Resources:
  Parameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Ref Enviroment
      Type: "String"
      Value: !Ref Enviroment
      Description: "Enviroment Prefix"
