apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: <your domain>
    http:
      paths:
      - backend:
          serviceName: <your service>
          servicePort: 80
  - host: <your subdomain>
    http:
      paths:
      - backend:
          serviceName: <your service>
          servicePort: 80
