apiVersion: v1
kind: Pod
metadata:
  name: test-pod-1
spec:
  containers:
  - image: fedora:latest
    name: tc-1
    volumeMounts:
    - mountPath: /var/www1
      name: host-volume
    command: ["tail",  "-f", "/dev/null"]
  - image: fedora:latest
    name: tc-2
    volumeMounts:
    - mountPath: /var/www1
      name: host-volume
    command: ["tail",  "-f", "/dev/null"]
  volumes:
  - name: host-volume
    hostPath:
      path: /www
      type: DirectoryOrCreate
